remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
tytitle: IQCT
description: Innovation on Quantum & CT
show_downloads: false
